build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
          - phpcs-run

checks:
  php: true

tools:
    php_sim: true
    php_pdepend: true
    php_mess_detector: true
    php_analyzer: true
    php_changetracking: true
    sensiolabs_security_checker: true
    php_code_sniffer:
        config:
            ruleset: PSR2
